/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class CustomerPage extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPage
     */
    public CustomerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutbtn = new javax.swing.JLabel();
        Historybtn = new javax.swing.JButton();
        transactionbtn = new javax.swing.JButton();
        infobtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        logoutbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(153, 0, 0));
        logoutbtn.setText("LogOut");
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        add(logoutbtn);
        logoutbtn.setBounds(570, 400, 90, 50);

        Historybtn.setBackground(new java.awt.Color(0, 153, 204));
        Historybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Historybtn.setText("Display transaction history");
        Historybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistorybtnMouseClicked(evt);
            }
        });
        add(Historybtn);
        Historybtn.setBounds(260, 210, 250, 100);

        transactionbtn.setBackground(new java.awt.Color(0, 153, 204));
        transactionbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transactionbtn.setText("New transaction");
        transactionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionbtnActionPerformed(evt);
            }
        });
        add(transactionbtn);
        transactionbtn.setBounds(260, 90, 250, 100);

        infobtn.setBackground(new java.awt.Color(0, 153, 204));
        infobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        infobtn.setText("Information setting");
        infobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infobtnMouseClicked(evt);
            }
        });
        add(infobtn);
        infobtn.setBounds(260, 330, 250, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcom =)");
        add(jLabel2);
        jLabel2.setBounds(580, 30, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 500));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void transactionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionbtnActionPerformed

    private void infobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infobtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_infobtnMouseClicked

    private void HistorybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorybtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorybtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Historybtn;
    public javax.swing.JButton infobtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel logoutbtn;
    public javax.swing.JButton transactionbtn;
    // End of variables declaration//GEN-END:variables
}
