/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;


public class LoginCustomerPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginCustomerPage
     */
    public LoginCustomerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Employeelbl = new javax.swing.JLabel();
        Creatlbl = new javax.swing.JLabel();
        logcbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        add(jLabel2);
        jLabel2.setBounds(160, 190, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(140, 240, 72, 30);

        nametxt.setBackground(new java.awt.Color(153, 153, 153));
        add(nametxt);
        nametxt.setBounds(220, 190, 240, 30);

        passtxt.setBackground(new java.awt.Color(153, 153, 153));
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        add(passtxt);
        passtxt.setBounds(220, 240, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Bank Managment System");
        add(jLabel4);
        jLabel4.setBounds(240, 30, 360, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("More option for ");
        add(jLabel5);
        jLabel5.setBounds(250, 120, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Do you have account?");
        add(jLabel6);
        jLabel6.setBounds(190, 350, 160, 17);

        Employeelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Employeelbl.setForeground(new java.awt.Color(204, 0, 0));
        Employeelbl.setText("Employee");
        Employeelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeelblMouseClicked(evt);
            }
        });
        add(Employeelbl);
        Employeelbl.setBounds(360, 110, 80, 40);

        Creatlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Creatlbl.setForeground(new java.awt.Color(204, 0, 0));
        Creatlbl.setText("Creat now");
        Creatlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreatlblMouseClicked(evt);
            }
        });
        add(Creatlbl);
        Creatlbl.setBounds(350, 350, 80, 17);

        logcbtn.setBackground(new java.awt.Color(255, 255, 255));
        logcbtn.setText("OK");
        logcbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logcbtnMouseClicked(evt);
            }
        });
        add(logcbtn);
        logcbtn.setBounds(300, 290, 47, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 500));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeelblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeelblMouseClicked

    private void CreatlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CreatlblMouseClicked

    private void logcbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logcbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logcbtnMouseClicked

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Creatlbl;
    public javax.swing.JLabel Employeelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton logcbtn;
    public javax.swing.JTextField nametxt;
    public javax.swing.JPasswordField passtxt;
    // End of variables declaration//GEN-END:variables
}
