/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;


public class LoginEmployeePage extends javax.swing.JPanel {

    /**
     * Creates new form LoginEmployeePage
     */
    public LoginEmployeePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameEtxt = new javax.swing.JTextField();
        loginEbtn = new javax.swing.JButton();
        passEtxt = new javax.swing.JPasswordField();
        BackEtoC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Bank Managment System");
        add(jLabel2);
        jLabel2.setBounds(260, 40, 302, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Welcom, have a nice day ");
        add(jLabel3);
        jLabel3.setBounds(350, 110, 170, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID:");
        add(jLabel4);
        jLabel4.setBounds(180, 210, 30, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password:");
        add(jLabel5);
        jLabel5.setBounds(160, 250, 80, 17);

        nameEtxt.setBackground(new java.awt.Color(153, 153, 153));
        add(nameEtxt);
        nameEtxt.setBounds(240, 200, 230, 30);

        loginEbtn.setBackground(new java.awt.Color(255, 255, 255));
        loginEbtn.setText("OK");
        loginEbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginEbtnMouseClicked(evt);
            }
        });
        add(loginEbtn);
        loginEbtn.setBounds(310, 290, 47, 23);

        passEtxt.setBackground(new java.awt.Color(153, 153, 153));
        passEtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passEtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passEtxtFocusLost(evt);
            }
        });
        passEtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passEtxtActionPerformed(evt);
            }
        });
        add(passEtxt);
        passEtxt.setBounds(240, 240, 230, 30);

        BackEtoC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackEtoC.setForeground(new java.awt.Color(51, 102, 0));
        BackEtoC.setText(">>BACK");
        BackEtoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackEtoCMouseClicked(evt);
            }
        });
        add(BackEtoC);
        BackEtoC.setBounds(60, 30, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 500));
        jLabel1.setRequestFocusEnabled(false);
        add(jLabel1);
        jLabel1.setBounds(-7, 2, 990, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void loginEbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginEbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEbtnMouseClicked

    private void passEtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passEtxtFocusGained
        // TODO add your handling code here:
        passEtxt.setText("");
    }//GEN-LAST:event_passEtxtFocusGained

    private void passEtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passEtxtFocusLost
        // TODO add your handling code here:
        passEtxt.setText("************");
    }//GEN-LAST:event_passEtxtFocusLost

    private void BackEtoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackEtoCMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BackEtoCMouseClicked

    private void passEtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passEtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passEtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BackEtoC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JButton loginEbtn;
    public javax.swing.JTextField nameEtxt;
    public javax.swing.JPasswordField passEtxt;
    // End of variables declaration//GEN-END:variables
}
