/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class TransactionPage extends javax.swing.JPanel {

    /**
     * Creates new form TransactionPage
     */
    public TransactionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depositbtn = new javax.swing.JButton();
        withdrawbtn = new javax.swing.JButton();
        transferbtn = new javax.swing.JButton();
        logoutlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        backlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backlbl.setForeground(new java.awt.Color(102, 153, 0));
        backlbl.setText(">> Back");
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
        });
        add(backlbl);
        backlbl.setBounds(50, 40, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Welcom =)");
        add(jLabel3);
        jLabel3.setBounds(580, 50, 90, 30);

        depositbtn.setBackground(new java.awt.Color(0, 153, 204));
        depositbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depositbtn.setText("Deposit");
        depositbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositbtnMouseClicked(evt);
            }
        });
        add(depositbtn);
        depositbtn.setBounds(290, 110, 200, 80);

        withdrawbtn.setBackground(new java.awt.Color(0, 153, 204));
        withdrawbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawbtn.setText("Withdraw");
        withdrawbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawbtnMouseClicked(evt);
            }
        });
        withdrawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbtnActionPerformed(evt);
            }
        });
        add(withdrawbtn);
        withdrawbtn.setBounds(293, 220, 200, 80);

        transferbtn.setBackground(new java.awt.Color(0, 153, 204));
        transferbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        transferbtn.setText("Transfer Into");
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });
        add(transferbtn);
        transferbtn.setBounds(290, 340, 200, 80);

        logoutlbl.setBackground(new java.awt.Color(153, 0, 0));
        logoutlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutlbl.setForeground(new java.awt.Color(153, 0, 0));
        logoutlbl.setText("LogOut");
        logoutlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlblMouseClicked(evt);
            }
        });
        add(logoutlbl);
        logoutlbl.setBounds(570, 420, 52, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 500));
        add(jLabel1);
        jLabel1.setBounds(-20, 0, 970, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backlblMouseClicked

    private void depositbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_depositbtnMouseClicked

    private void withdrawbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawbtnMouseClicked

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferbtnActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void logoutlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutlblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel backlbl;
    public javax.swing.JButton depositbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel logoutlbl;
    public javax.swing.JButton transferbtn;
    public javax.swing.JButton withdrawbtn;
    // End of variables declaration//GEN-END:variables
}
