/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class AfTransfer extends javax.swing.JPanel {

    /**
     * Creates new form AfTransfer
     */
    public AfTransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moneyttxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        accountxt1 = new javax.swing.JTextField();
        confirmbtn = new javax.swing.JButton();
        backlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("....  Review ....");
        add(jLabel1);
        jLabel1.setBounds(310, 80, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("You are tring to transfer to ");
        add(jLabel2);
        jLabel2.setBounds(300, 150, 180, 50);

        moneyttxt.setEditable(false);
        moneyttxt.setBackground(new java.awt.Color(204, 204, 204));
        add(moneyttxt);
        moneyttxt.setBounds(300, 330, 170, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Amount of money");
        add(jLabel3);
        jLabel3.setBounds(330, 290, 140, 40);

        accountxt1.setEditable(false);
        accountxt1.setBackground(new java.awt.Color(204, 204, 204));
        add(accountxt1);
        accountxt1.setBounds(300, 200, 170, 70);

        confirmbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirmbtn.setText("Confirm");
        confirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmbtnMouseClicked(evt);
            }
        });
        add(confirmbtn);
        confirmbtn.setBounds(330, 430, 110, 30);

        backlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backlbl.setText(">>BACK");
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
        });
        add(backlbl);
        backlbl.setBounds(70, 40, 47, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmbtnMouseClicked

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backlblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField accountxt1;
    public javax.swing.JLabel backlbl;
    public javax.swing.JButton confirmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField moneyttxt;
    // End of variables declaration//GEN-END:variables
}
