/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class Deposit extends javax.swing.JPanel {

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        backlbl = new javax.swing.JLabel();
        moneytxt = new javax.swing.JTextField();
        confirmbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter amount of money");
        add(jLabel3);
        jLabel3.setBounds(280, 140, 240, 40);

        backlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backlbl.setForeground(new java.awt.Color(51, 102, 0));
        backlbl.setText(">>BACK");
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
        });
        add(backlbl);
        backlbl.setBounds(50, 30, 70, 14);

        moneytxt.setBackground(new java.awt.Color(102, 102, 102));
        moneytxt.setForeground(new java.awt.Color(255, 255, 255));
        moneytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneytxtActionPerformed(evt);
            }
        });
        add(moneytxt);
        moneytxt.setBounds(250, 190, 290, 70);

        confirmbtn.setText("Confirm");
        confirmbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmbtnMouseClicked(evt);
            }
        });
        add(confirmbtn);
        confirmbtn.setBounds(370, 330, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Welcom =)");
        add(jLabel2);
        jLabel2.setBounds(554, 60, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(808, 488));
        add(jLabel1);
        jLabel1.setBounds(0, -20, 1000, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backlblMouseClicked

    private void confirmbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmbtnMouseClicked

    private void moneytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneytxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel backlbl;
    public javax.swing.JButton confirmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField moneytxt;
    // End of variables declaration//GEN-END:variables
}
