/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class EmployeePage extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePage
     */
    public EmployeePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletebtn = new javax.swing.JButton();
        viewlbl = new javax.swing.JButton();
        openbtn = new javax.swing.JButton();
        logoutlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(173, 208, 218));
        setLayout(null);

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletebtn.setText("Delete customer");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });
        add(deletebtn);
        deletebtn.setBounds(40, 320, 200, 80);

        viewlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewlbl.setText("View customer information");
        viewlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewlblMouseClicked(evt);
            }
        });
        add(viewlbl);
        viewlbl.setBounds(40, 80, 200, 80);

        openbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        openbtn.setText("Open new account");
        openbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openbtnMouseClicked(evt);
            }
        });
        openbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openbtnActionPerformed(evt);
            }
        });
        add(openbtn);
        openbtn.setBounds(40, 200, 200, 80);

        logoutlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutlbl.setForeground(new java.awt.Color(102, 0, 0));
        logoutlbl.setText("LogOut");
        logoutlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlblMouseClicked(evt);
            }
        });
        add(logoutlbl);
        logoutlbl.setBounds(550, 190, 220, 130);

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/BB.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void openbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openbtnActionPerformed

    private void logoutlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutlblMouseClicked

    private void viewlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewlblMouseClicked

    private void openbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_openbtnMouseClicked

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel logoutlbl;
    public javax.swing.JButton openbtn;
    public javax.swing.JButton viewlbl;
    // End of variables declaration//GEN-END:variables
}
