/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class OpenC extends javax.swing.JPanel {

    /**
     * Creates new form OpenC
     */
    public OpenC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backlbl = new javax.swing.JLabel();
        viewlbl = new javax.swing.JButton();
        openbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        addrtxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        registerbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(173, 208, 218));
        setLayout(null);

        backlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backlbl.setText(">>Back");
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
        });
        add(backlbl);
        backlbl.setBounds(10, 20, 60, 14);

        viewlbl.setBackground(new java.awt.Color(255, 255, 255));
        viewlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewlbl.setText("View customer information");
        viewlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewlblMouseClicked(evt);
            }
        });
        add(viewlbl);
        viewlbl.setBounds(40, 80, 200, 80);

        openbtn.setBackground(new java.awt.Color(102, 102, 102));
        openbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        openbtn.setText("Open new account");
        openbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openbtnActionPerformed(evt);
            }
        });
        add(openbtn);
        openbtn.setBounds(40, 200, 200, 80);

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletebtn.setText("Delete customer");
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });
        add(deletebtn);
        deletebtn.setBounds(40, 320, 200, 80);

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/BB.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 530);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(294, 50, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel3.setText("ID");
        add(jLabel3);
        jLabel3.setBounds(294, 90, 40, 15);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel4.setText("Address");
        add(jLabel4);
        jLabel4.setBounds(294, 130, 50, 15);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel5.setText("DOB");
        add(jLabel5);
        jLabel5.setBounds(294, 170, 40, 15);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel6.setText("Email");
        add(jLabel6);
        jLabel6.setBounds(294, 210, 40, 15);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel7.setText("Phone");
        add(jLabel7);
        jLabel7.setBounds(294, 250, 40, 15);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel9.setText("Password");
        add(jLabel9);
        jLabel9.setBounds(290, 290, 60, 15);
        add(nametxt);
        nametxt.setBounds(370, 40, 320, 30);

        dobtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobtxtActionPerformed(evt);
            }
        });
        add(dobtxt);
        dobtxt.setBounds(370, 160, 320, 30);

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        add(emailtxt);
        emailtxt.setBounds(370, 200, 320, 30);
        add(phonetxt);
        phonetxt.setBounds(370, 240, 320, 30);

        addrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtxtActionPerformed(evt);
            }
        });
        add(addrtxt);
        addrtxt.setBounds(370, 120, 320, 30);

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        add(idtxt);
        idtxt.setBounds(370, 80, 320, 30);
        add(passtxt);
        passtxt.setBounds(370, 280, 320, 30);

        registerbtn.setText("Regist");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });
        add(registerbtn);
        registerbtn.setBounds(470, 380, 90, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backlblMouseClicked

    private void viewlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewlblMouseClicked

    private void openbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openbtnActionPerformed

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnMouseClicked

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void addrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtxtActionPerformed

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtnMouseClicked

    private void dobtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobtxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField addrtxt;
    public javax.swing.JLabel backlbl;
    public javax.swing.JButton deletebtn;
    public javax.swing.JTextField dobtxt;
    public javax.swing.JTextField emailtxt;
    public javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nametxt;
    public javax.swing.JButton openbtn;
    public javax.swing.JPasswordField passtxt;
    public javax.swing.JTextField phonetxt;
    public javax.swing.JButton registerbtn;
    public javax.swing.JButton viewlbl;
    // End of variables declaration//GEN-END:variables
}
