/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagment;

/**
 *
 * @author Nabaa
 */
public class Transaction extends javax.swing.JPanel {

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accounttxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        moneytxt = new javax.swing.JTextField();
        continuebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        backlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backlbl.setForeground(new java.awt.Color(51, 102, 0));
        backlbl.setText(">>BACK");
        backlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlblMouseClicked(evt);
            }
        });
        add(backlbl);
        backlbl.setBounds(40, 30, 90, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Welcom =)");
        add(jLabel2);
        jLabel2.setBounds(590, 70, 70, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Enter the person's account number");
        add(jLabel3);
        jLabel3.setBounds(270, 130, 280, 17);

        accounttxt.setBackground(new java.awt.Color(204, 204, 204));
        accounttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accounttxtActionPerformed(evt);
            }
        });
        add(accounttxt);
        accounttxt.setBounds(260, 170, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Enter amount of money");
        add(jLabel4);
        jLabel4.setBounds(300, 250, 220, 17);

        moneytxt.setBackground(new java.awt.Color(204, 204, 204));
        moneytxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                moneytxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                moneytxtFocusLost(evt);
            }
        });
        add(moneytxt);
        moneytxt.setBounds(259, 280, 260, 40);

        continuebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        continuebtn.setText("Countine");
        continuebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continuebtnMouseClicked(evt);
            }
        });
        add(continuebtn);
        continuebtn.setBounds(360, 400, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagment/B1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void backlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backlblMouseClicked

    private void moneytxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moneytxtFocusGained
        // TODO add your handling code here:
        moneytxt.setText("");
    }//GEN-LAST:event_moneytxtFocusGained

    private void moneytxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moneytxtFocusLost
        // TODO add your handling code here:
        moneytxt.setText("Amount of money");
    }//GEN-LAST:event_moneytxtFocusLost

    private void continuebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continuebtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_continuebtnMouseClicked

    private void accounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accounttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accounttxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField accounttxt;
    public javax.swing.JLabel backlbl;
    public javax.swing.JButton continuebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField moneytxt;
    // End of variables declaration//GEN-END:variables
}
